FaceAttendance/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('account/',include('account.urls')),
    path('student/',include('student.urls')),
    path('teacher/',include('teacher.urls')),
    path('Attendance/',include('Attendance.urls')),

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

account/urls.py
from django.contrib import admin
from django.urls import path,include
from account import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name='account' 

urlpatterns = [
    
    path('student/login/', views.student_login,name="student_login"),
    path('admin/login/', views.admin_login,name="admin_login"),
    path('student/register/', views.student_register.as_view(),name="student_register"),
    path('teacher/login/', views.teacher_login,name="teacher_login"),
    path('teacher/register/', views.teacher_register.as_view(),name="teacher_register"),
    path('change_password/student/$', views.change_password_stu,name="change_password_stu"),
    path('change_password/teacher/$', views.change_password_teach,name="change_password_teach"),

    path('password_reset/',auth_views.PasswordResetView.as_view(
            template_name='account/password/password_reset_form.html',
            email_template_name="account/password/password_reset_email.html",
            success_url=reverse_lazy('account:password_reset_done'),),
            name="reset_password"),

    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
            template_name='account/password/password_reset_done.html'), 
            name="password_reset_done"),

    path('password_reset/confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(
            template_name='account/password/password_reset_confirm.html',
            success_url=reverse_lazy('account:password_reset_complete'),), 
            name='password_reset_confirm'),

    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(
            template_name='account/password/password_reset_complete.html'),
            name="password_reset_complete"),      

] 

faceattandance/faceattandance/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

teacher/urls.py
from django.contrib import admin
from django.urls import path,include
from teacher import views

app_name ="teacher"


urlpatterns = [

    path('profile/', views.teacher_profile,name="teacher_profile"),
    path('logout/', views.teacher_logout,name="teacher_logout"),
    path('excel/', views.excel_report,name="excel_report"),
    path('dashboard/', views.teacher_dashboard,name="teacher_dashboard"),
    path('time_table/',views.ttime_table,name="ttime_table"),

]

teacher/models.py
from django.db import models

# Create your models here.

teacher/forms.py
from django.contrib.auth.forms import User
from django.contrib.auth.forms import UserChangeForm
from django import forms
from account.models import User,Teacher
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.forms import ModelForm

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    password = None
    class Meta:
        model = User
        fields = ['username','email',]

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = ['first_name','last_name','department','subject','image',]


    

teacher/views.py
from django.shortcuts import render,redirect,HttpResponse
from account.views import student_login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages,auth
from django.db import transaction
from django.contrib.auth.forms import UserChangeForm
from teacher.forms import ProfileUpdateForm, UserUpdateForm
from Attendance.models import Student_attendance, TimeTable
import xlwt
import datetime
from account.models import Teacher


def ttime_table(request):
    dept = request.user.teacher.department
    subject = request.user.teacher.subject
    m1 = TimeTable.objects.filter(department_id=dept, subject_id=subject)
    m2 = m1
    return render(request, 'teacher/ttime_table.html', {'m1': m1, 'm2': m2})
    
    
def teacher_dashboard(request):
    return render(request,'teacher/teacher_portal.html')

@login_required
def teacher_logout(request):
    auth.logout(request)
    return redirect('home')

@login_required
def teacher_profile(request):       
    if request.method == "POST":
        fm = UserUpdateForm(request.POST,instance=request.user)
        fm1 = ProfileUpdateForm(request.POST,
                                request.FILES,
                                instance=request.user.teacher)
        if fm.is_valid() and fm1.is_valid():
            fm.save()
            fm1.save()
            messages.success(request,f"Your profile has updated!!!")
            return redirect('teacher:teacher_profile')
    else:
        fm = UserUpdateForm(instance=request.user)
        fm1 = ProfileUpdateForm(instance=request.user.teacher)
        # return render(request,'student/student_profile.html',{'name':request.user,'name':request.user.student,'fm':fm, 'fm1':fm1})
    
    return render(request,'teacher/teacher_profile.html',{'fm':fm, 'fm1':fm1})
    
@login_required
def excel_report(request):
    teach_sub = request.user.teacher.subject
    
    if(teach_sub is None):
        messages.info(request,"You dont have any subject selected")
        return redirect('teacher:teacher_dashboard')
    else:
        response = HttpResponse(content_type='application/ms-excel')
        response['Content-Disposition'] = 'attachment; filename = Attendance-' + \
                    str(datetime.datetime.now())+'.xls'
        wb = xlwt.Workbook(encoding = 'utf-8')
        ws = wb.add_sheet('Attendance')
        row_num = 0
        font_style = xlwt.XFStyle()
        font_style.font.bold = True
        columns = ["Attendance Id","Subject","Attendance Date","Attendance Time",
                        "Student Name","Student Roll_no"]
        for col in range(len(columns)):
            ws.write(row_num,col,columns[col],font_style)

        rows = Student_attendance.objects.filter(subject = teach_sub)
        
        a = [x.attend_id for x in rows]
        b = [x.subject for x in rows]
        c = [x.attend_date for x in rows]
        d = [x.attend_time for x in rows]
        e = [x.student for x in rows]
        f = [x.student.roll_no for x in rows]
        data = [a,b,c,d,e,f]
        
        k=0
        for i in data:
            
            row_num = 0
            for j in range(len(i)):
                row_num += 1
                ws.write(row_num,k,str(i[j]),font_style)
            k += 1
        wb.save(response)

        return response
    
    
    

teacher/templates/teacher/teacher_portal.html
{% extends "base_dashboard.html" %}
{% load static %}

{% block user_type %}
    <a href="{% url 'teacher:teacher_dashboard' %}" class="navbar-brand dash">Teacher DashBoard</a>
{% endblock %}

{% block myblock %}
{% if user.is_superuser or user.is_student %}
    <div class="container">
        <div class="row">
            <div class="col-md-12 mt-4">
                <div class="jumbotron">
                    <h1>Sorry Mr./Miss {{user.username}} You are not allowed Here</h1>
                </div>
            </div>
        </div>
    </div>
{% else %}

{% block profile %} <a href="{% url 'teacher:teacher_profile' %}" class="btn btn-outline-light">Profile</a>{% endblock %}
<div class="container-fluid my-0" style="margin-top: 5px;" >
					{% for message in messages %}
                    <div class="alert alert-success alert-dismissible fade show">
                        <strong>{{ message }}.</strong>
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                    </div>
                    {% endfor %} 
    <div class="row">
        <!-- left side menu -->
        <div class="col-md-2 bg-dark py-5">
            <nav class="navbar navbar-dark">
                <a href="{% url 'teacher:teacher_dashboard' %}" class="navbar-brand">
                    <div class="text-center">
                        {% if request.user.teacher.image %}
                        <img class="rounded-circle profile-img" src="{{request.user.teacher.image.url}}" width="170" height="170">
                        {% else %}
                            <img class="rounded-circle profile-img" src="{% static '/teacher/profile.png' %}" width="170" height="170">
                        {% endif %}             
                        <p class="username">{{user.username}}</p>
                    </div>
                </a>                
                <ul class="navbar-nav border-bottom">                   
                    <li class="nav-item">
                        <a href="{% url 'account:change_password_teach' %}" class="nav-link">Change Password</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'teacher:teacher_profile' %}" class="nav-link">Edit Profile</a>
                    </li>
                </ul>

            </nav>
        </div>

        <!-- right side menu -->
        <div class="container">
        {% block dashboard %}
            <div style="margin-top:40px" class="col-md-10 col-lg-10">                
                    
                <!-- 2nd menu -->            
                <div class="row dash-menu">  
                    <div class="col-md-4 col-lg-4">
                        <img src="{% static 'student/report.png' %}">
                        <p class="dash-stu-heading">Attendance Sheet</p>
                    </div>
                    <div class="col-md-6 col-lg-6 menu-desc">
                        <p class="dash-stu-descr"> See attendance record of your lecture and download it in excel formate(.xls)</p>
                        <div class="dash-stu-btn">
                            <a class="btn btn-secondary" href="{% url 'teacher:excel_report' %}">Download Attendance</a>
                        </div>
                    </div>
                </div>
                
                <!-- 3rd menu -->
                <div class="row dash-menu">
                    <div class="col-md-4 col-lg-4">
                        <img src="{% static 'student/tt.png' %}">
                        <p class="dash-stu-heading">Schedule</p>
                    </div>
                    <div class="col-md-6 col-lg-6 menu-desc">
                        <p class="dash-stu-descr"> See your all lecture schedule in by day ,time and semester</p>
                        <div class="dash-stu-btn">
                            <a class="btn btn-secondary" href="{% url 'teacher:ttime_table' %}">See Schedule</a>
                        </div>
                    </div> 
                </div>   
            </div>
            {% endblock %}
        </div>
    </div>
</div>
{% endif %}

{% endblock %}

teacher/templates/teacher/teacher_profile.html
{% extends 'teacher/teacher_portal.html' %}
{% load static %}
{% block title %}Profile | {{request.user.username}}{% endblock title %}

{% block dashboard %}

<div style="margin-top:40px" class=" r col-md-10 col-lg-10">
  {% for message in messages %}
  <div class="alert alert-success alert-dismissible fade show">
    <strong>{{ message }}.</strong>
    <button type="button" class="close" data-dismiss="alert">&times;</button>
  </div>
{% endfor %}
  <div class="row dash-menu">
    <form action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}        
          <p style="font-size: 30px;">Profile Setting</p>
          <div class="row">
            <div class="col-lg-5 col-md-5">{{fm.username.label_tag}}</div>
            <div class="col-lg-5 col-md-5">{{fm.username}}</div>
          </div>

          <div class="row">
            <div class="col-lg-5 col-md-5">{{fm.email.label_tag}}</div>
            <div class="col-lg-5 col-md-5 dbox">{{fm.email}}</div>
      </div>
          <div class="row">
            <div class="col-lg-5 col-md-5">{{fm1.first_name.label_tag}} </div>
            <div class="col-lg-5 col-md-5 dbox">{{fm1.first_name}}</div>
          </div>
          <div class="row">
            <div class="col-lg-5 col-md-5">{{fm1.last_name.label_tag}}</div>
            <div class="col-lg-5 col-md-5 dbox">{{fm1.last_name}}</div>
          </div>
          <div class="row">
            <div class="col-lg-5 col-md-5"> {{fm1.subject.label_tag}} </div>
            <div class="col-lg-5 col-md-5 dbox">{{fm1.subject}}</div>
          </div>
          <div class="row">
            <div class="col-lg-5 col-md-5">{{fm1.contact_no.label_tag}} </div>
            <div class="col-lg-5 col-md-5 dbox">{{fm1.contact_no}}</div>
          </div>
          <div class="row">
            <div class="col-lg-5 col-md-5"> {{fm1.department.label_tag}}  </div>
            <div class="col-lg-5 col-md-5 dbox">{{fm1.department}}</div>
          </div>
          <div class="row">
            <div class="col-lg-5 col-md-5"> {{fm1.image.label_tag}} </div>
            <div class="col-lg-5 col-md-5 dbox">{{fm1.image}}</div>
          </div>
                        
          <div class="col-lg-8 col-md-8 " style="margin-top: 30px;">
            <button class="btn btn-secondary" type="submit">Save changes</button>
          </div>           
    </form>
  </div>

</div>
{% endblock %}

teacher/templates/teacher/ttime_table.html
{% extends 'teacher/teacher_portal.html' %}
{% load static %}
{% block title %}Time Table | {{request.user.username}}{% endblock title %}

{% block css %}    
  <style>
    .time{
      font-size: 30px; 
      border-bottom: rgb(136, 136, 138) solid 5px;
      width: 150px;
    }
    table{
      border-radius: 20px;
    }
    th,tr,td{
      padding: 20px;
      border-bottom: rgb(219, 216, 216) 1px solid;
      color: #777;
    }
    th{
      color: rgb(87, 87, 87);
      font-size: 20px;
    }
  </style>
{% endblock %}

{% block dashboard %}
<h1 class="time">Your Schedule</h1>
<table class="dash-menu" align=center>

					<tr align=center>
						<th colspan = 5>{{request.user.student.department}}</th>
					</tr>
                    <tr>
                        <th>Day</th>
                        <th>Start time</th>
                        <th>End time</th>
                        <th>Subject</th>
						<th>Semester</th>

                    </tr>
                    {% for m in m1 %}
                    <tr>
                        <td>{{m.day}}</td>
                        <td>{{m.start_time}}</td>
                        <td>{{m.end_time}}</td>
                        <td>{{m.subject_id}}</td>
						<td>{{m.sem}}</td>

						
                    </tr>
                    {% endfor %}
            </table>
        
{% endblock %}