Attendance/urls.py
from django.contrib import admin
from django.urls import path,include
from Attendance import views

app_name ="Attendance"

urlpatterns = [    
    path('training/', views.train_model,name="train_model"),
    path('testing/', views.test_model,name="test_model"),
    path("select_sub/",views.select_sub,name="select_sub"),
    path('dataset/',views.create_dataset,name="create_dataset"),
    path('attendance',views.attendance,name="attendance"),
    path('add_schedule',views.add_schedule,name="add_schedule")
]

FaceAttendance/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('account/',include('account.urls')),
    path('student/',include('student.urls')),
    path('teacher/',include('teacher.urls')),
    path('Attendance/',include('Attendance.urls')),

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

account/urls.py
from django.contrib import admin
from django.urls import path,include
from account import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name='account' 

urlpatterns = [
    
    path('student/login/', views.student_login,name="student_login"),
    path('admin/login/', views.admin_login,name="admin_login"),
    path('student/register/', views.student_register.as_view(),name="student_register"),
    path('teacher/login/', views.teacher_login,name="teacher_login"),
    path('teacher/register/', views.teacher_register.as_view(),name="teacher_register"),
    path('change_password/student/$', views.change_password_stu,name="change_password_stu"),
    path('change_password/teacher/$', views.change_password_teach,name="change_password_teach"),

    path('password_reset/',auth_views.PasswordResetView.as_view(
            template_name='account/password/password_reset_form.html',
            email_template_name="account/password/password_reset_email.html",
            success_url=reverse_lazy('account:password_reset_done'),),
            name="reset_password"),

    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
            template_name='account/password/password_reset_done.html'), 
            name="password_reset_done"),

    path('password_reset/confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(
            template_name='account/password/password_reset_confirm.html',
            success_url=reverse_lazy('account:password_reset_complete'),), 
            name='password_reset_confirm'),

    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(
            template_name='account/password/password_reset_complete.html'),
            name="password_reset_complete"),      

] 

faceattandance/faceattandance/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

student/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from Attendance.views import select_sub

app_name ="student"

urlpatterns = [

    path('profile/', views.student_profile,name="student_profile"),
    path('logout/', views.student_logout,name="student_logout"),
    path('dashboard/', views.student_dashboard,name="student_dashboard"),
    path('time_table/',views.time_table,name="time_table"),
    path('report/',views.attendance_report,name="attendance_report"),
  
]

Attendance/models.py
from django.db import models
from account.models import Department,Subject,Teacher,Student
from django.utils import timezone
from django.utils.translation import gettext_lazy as _ 
from datetime import datetime

class TimeTable(models.Model):
    time_id = models.IntegerField(primary_key=True)
    day = models.CharField(max_length = 20)
    start_time = models.CharField(max_length = 5)
    end_time = models.CharField(max_length = 5)
    sem = models.CharField(max_length = 5)
    department_id = models.ForeignKey(Department,on_delete=models.CASCADE)
    subject_id = models.ForeignKey(Subject,on_delete=models.CASCADE)
    teacher = models.ForeignKey(Teacher,on_delete=models.CASCADE)


class Student_attendance(models.Model):
    def to_time(value):   
        hhmm1 = value.split(' ')
        hhmm2 = str(hhmm1[1])
        hhmm = hhmm2[:5]
        now = datetime.now()
        current_time = now.strftime("%H:%M")
        return hhmm

    attend_id = models.IntegerField(primary_key=True)
    subject = models.ForeignKey(Subject,on_delete=models.CASCADE)
    status = models.BooleanField(default=False)
    attend_date = models.DateField(auto_now_add = True)
    attend_time = models.TimeField(default=datetime.now().strftime("%H:%M"))
    student = models.ForeignKey(Student,on_delete=models.CASCADE)


    def __str__(self):
        return str(self.subject)

Attendance/views.py
from django.shortcuts import render,redirect,HttpResponse
from django.contrib.auth.decorators import login_required
from Attendance.face_recognition import custom_dataset as cd
from Attendance.face_recognition import encode_faces as ef
from student.views import student_dashboard
from Attendance.face_recognition import face_identify as fi
from student.forms import SelectSubForm
from Attendance.models import Student_attendance, TimeTable
from django.contrib import messages
from datetime import datetime

@login_required
def add_schedule(request):
    return render(request,"Attendance/add_schedule.html")

@login_required
def create_dataset(request):
    if request.user.is_authenticated and request.user.is_superuser == 1:
        name = request.user.student.first_name
        cd.function(name)
    else:
        return HttpResponse("<h1>You are not allowed!!!</h1>")
    return redirect('Attendance:attendance')

@login_required
def train_model(request):
    if request.user.is_authenticated:
        path = 'E://anchal/FinalYearProject/FaceAttendance/Attendance/face_recognition/dataset'
        ef.train_models(path)
    return redirect('Attendance:attendance') 


@login_required
def test_model(request):
    if request.user.is_authenticated:
        fi.test_models()
    return redirect('Attendance:attendance') 

@login_required
def attendance(request):
    return render(request,'Attendance/attendance.html')

@login_required
def select_sub(request):
    if request.method == "POST":
        form = SelectSubForm(request.user,request.POST)
        if form.is_valid():
            sub = form.cleaned_data.get('subject')
            print("OPENING CAMERA.......\n\n\n")
            if request.user.is_authenticated:
                today = datetime.now()
                day = today.strftime("%A")
                if((day == 'Saturday') or (day == 'Sunday')):
                    messages.success(request, 'Today is holiday..!!')                    
                    return redirect('student:student_dashboard')
                try:
                    m1 = TimeTable.objects.get(day = day, subject_id = sub)
                except:
                    messages.success(request, f"There is no lecture of {sub}..!!")                    
                    return redirect('student:student_dashboard')

                now = datetime.now() 
                curr = now.strftime("%H:%M")
                s = datetime.strptime(str(curr), "%H:%M")#12 formate
                current_time = str(s.strftime("%I:%M"))#final
                ct = str(current_time).split(":")
                tt = '01:50'.split(":")#09:50
                print(current_time,"\n\nhhhhhh")

                if(ct[0] == tt[0] and int(ct[1]) <= int(int(tt[1])+5)):
                    matched_name = fi.test_models()                           
                    if(matched_name == request.user.username):        
                        attend = Student_attendance(subject = sub,status = True,student = request.user.student)
                        attend.save() 
                        messages.success(request, 'Your attendance has been marked..!!')
                    else:
                        messages.success(request, 'You are not authenticated for attendance..!!')
                    return redirect('student:student_dashboard') 
                
                else:
                    messages.success(request, 'This time you are not allowed to give attendance..!!')
                    return redirect('student:student_dashboard') 

        else:
            form = SelectSubForm(request.user)
            messages.success(request,f"Please select subject!!")
            return render(request,'student/select_sub.html',{'fm':form})
    else:
        form = SelectSubForm(request.user)
        return render(request,'student/select_sub.html',{'fm':form})












































































































    # face_recognizer=cv2.face.LBPHFaceRecognizer_create()
    # face_recognizer.read('Attendance/trainingData.yml')

    # name={2:"Ujala",1:"Anchal"}

    # cap = cv2.VideoCapture(0)

    # while True:
        
    #     ret,test_img=cap.read()# captures frame and returns boolean value and captured image
    #     faces_detected,gray_img=fr.faceDetection(test_img)

    #     for face in faces_detected:
    #         (x,y,w,h)=face
    #         roi_gray=gray_img[y:y+w, x:x+h]
    #         label,confidence=face_recognizer.predict(roi_gray)#predicting the label of given image
    #         print("confidence:",confidence)
    #         print("label:",label)
    #         fr.draw_rect(test_img,face)
    #         predicted_name=name[label]
    #         if confidence <= 50:#If confidence less than 37 then don't print predicted face text on screen
    #             fr.put_text(test_img,predicted_name,x,y)
    #         else:
    #             if confidence > 50:#If confidence less than 37 then don't print predicted face text on screen
    #                 fr.put_text(test_img,"Unknown",x,y)

    #         attendstudent = predicted_name

    #     resized_img = cv2.resize(test_img, (1000, 700))
    #     cv2.imshow('face recognition tutorial ',resized_img)
    #     if cv2.waitKey(10) == ord('q'):#wait until 'q' key is pressed
    #         break

    # cap.release()
    # cv2.destroyAllWindows
    # return redirect('student:student_dashboard')

Attendance/templates/Attendance/add_schedule.html
{% extends 'base_dashboard.html' %}
{% load static %}
{% block title %}Add schedule | {{request.user.username}}{% endblock title %}

{% block myblock %}

  {% block user_type %}
      <a href="{% url 'Attendance:attendance' %}" class="navbar-brand">Admin DashBoard</a>
  {% endblock %}

<div style="margin-top:40px" class=" r col-md-10 col-lg-10">
  {% for message in messages %}
  <div class="alert alert-success alert-dismissible fade show">
    <strong>{{ message }}.</strong>
    <button type="button" class="close" data-dismiss="alert">&times;</button>
  </div>
  {% endfor %}

  <div class="row dash-menu">
    <form action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}        
          <p style="font-size: 30px;">Add Schedule</p>
          <div class="row ">
            <div class="col-lg-5 col-md-5">{{fm.username.label_tag}}</div>
            <div class="col-lg-5 col-md-5">{{fm.username}}</div>
          </div>
          <div class="row">
            <div class="col-lg-5 col-md-5">{{fm.email.label_tag}}</div>
            <div class="col-lg-5 col-md-5 dbox">{{fm.email}}</div>
          </div>
          <div class="row">
            <div class="col-lg-5 col-md-5">{{fm1.first_name.label_tag}} </div>
            <div class="col-lg-5 col-md-5 dbox">{{fm1.first_name}}</div>
          </div>
          <div class="row">
            <div class="col-lg-5 col-md-5">{{fm1.last_name.label_tag}}</div>
            <div class="col-lg-5 col-md-5 dbox">{{fm1.last_name}}</div>
          </div>
          <div class="row">
            <div class="col-lg-5 col-md-5">{{fm1.roll_no.label_tag}}</div>
            <div class="col-lg-5 col-md-5 dbox">{{fm1.roll_no}}</div>
          </div>
          <div class="row">
            <div class="col-lg-5 col-md-5"> {{fm1.semester.label_tag}} </div>
            <div class="col-lg-5 col-md-5 dbox">{{fm1.semester}}</div>
          </div>
          <div class="row">
            <div class="col-lg-5 col-md-5">{{fm1.contact_no.label_tag}} </div>
            <div class="col-lg-5 col-md-5 dbox">{{fm1.contact_no}}</div>
          </div>
          <div class="row">
            <div class="col-lg-5 col-md-5"> {{fm1.department.label_tag}}  </div>
            <div class="col-lg-5 col-md-5 dbox">{{fm1.department}}</div>
          </div>
          <div class="row">
            <div class="col-lg-5 col-md-5"> {{fm1.image.label_tag}} </div>
            <div class="col-lg-5 col-md-5 dbox">{{fm1.image}}</div>
          </div>
          <div class="col-lg-8 col-md-8 " style="margin-top: 30px;">
            <button class="btn btn-secondary" type="submit">save schedule</button>
          </div>           
    </form>
  </div>

</div>
{% endblock %}

Attendance/templates/Attendance/attendance.html
{% extends "base_dashboard.html" %}
{% load static %}

{% block myblock %}

{% block user_type %}
    <a href="{% url 'Attendance:attendance' %}" class="navbar-brand dash">Admin DashBoard</a>
{% endblock %}

{% if user.is_teacher or user.is_student %}
    <div class="container">
        <div class="row">
            <div class="col-md-12 mt-4">
                <div class="jumbotron">
                    <h1>Sorry Mr./Miss {{user.username}} You are not allowed Here</h1>
                </div>
            </div>
        </div>
    </div>
{% else %}

<!-- <div class="previous">
    <a href="{% url 'student:student_dashboard' %}"><span class="fa fa-long-arrow-left"></span> Go Back</a>
</div> -->

<center><h2>Face Recognition and Detection Page</h2>

<div class="col-lg-4 col-md-4 " style="margin-top: 30px;">
    <a href="{% url 'Attendance:create_dataset' %}" class="btn btn-secondary" type="submit">Create dataset</a>
</div>

<div class="col-lg-4 col-md-4 " style="margin-top: 30px;">
    <a href="{% url 'Attendance:train_model' %}" class="btn btn-secondary" type="submit">Train model</a>
</div>

<div class="col-lg-4 col-md-4 " style="margin-top: 30px;">
    <a href="{% url 'Attendance:test_model' %}" class="btn btn-secondary" type="submit">Test model</a>
</div>


</center>
{% endif %}

{% endblock %}

Attendance/templates/Attendance/testing_webcam.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Attendane | Testing</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        .previous{
            margin: 20px;
            background-color: #777;
            padding: 10px;
            padding-left: 20px;
            width: 400px;
            border-radius: 20px;
        }
        .previous a{
            color: white;
            text-decoration: none;
        }
    </style>
</head>
<body style="background-color: #f7f7f7;">
    <div class="previous">
        <a href="{% url 'student:student_dashboard' %}"><span class="fa fa-long-arrow-left"></span> Go Back</a>
    </div>
    <center><h2>Face Recognition and Detection Page</h2></center>
    <!-- <img src="{% static 'student/attendance.jpg' %}"> -->
   
    <img src="{% url 'Attendanevideo_feed' %}">
    <img src="{% url 'webcam_feed' %}">

</body>
</html>