Attendance/urls.py
from django.contrib import admin
from django.urls import path,include
from Attendance import views

app_name ="Attendance"

urlpatterns = [    
    path('training/', views.train_model,name="train_model"),
    path('testing/', views.test_model,name="test_model"),
    path("select_sub/",views.select_sub,name="select_sub"),
    path('dataset/',views.create_dataset,name="create_dataset"),
    path('attendance',views.attendance,name="attendance"),
    path('add_schedule',views.add_schedule,name="add_schedule")
]

FaceAttendance/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('account/',include('account.urls')),
    path('student/',include('student.urls')),
    path('teacher/',include('teacher.urls')),
    path('Attendance/',include('Attendance.urls')),

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

account/urls.py
from django.contrib import admin
from django.urls import path,include
from account import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name='account' 

urlpatterns = [
    
    path('student/login/', views.student_login,name="student_login"),
    path('admin/login/', views.admin_login,name="admin_login"),
    path('student/register/', views.student_register.as_view(),name="student_register"),
    path('teacher/login/', views.teacher_login,name="teacher_login"),
    path('teacher/register/', views.teacher_register.as_view(),name="teacher_register"),
    path('change_password/student/$', views.change_password_stu,name="change_password_stu"),
    path('change_password/teacher/$', views.change_password_teach,name="change_password_teach"),

    path('password_reset/',auth_views.PasswordResetView.as_view(
            template_name='account/password/password_reset_form.html',
            email_template_name="account/password/password_reset_email.html",
            success_url=reverse_lazy('account:password_reset_done'),),
            name="reset_password"),

    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
            template_name='account/password/password_reset_done.html'), 
            name="password_reset_done"),

    path('password_reset/confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(
            template_name='account/password/password_reset_confirm.html',
            success_url=reverse_lazy('account:password_reset_complete'),), 
            name='password_reset_confirm'),

    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(
            template_name='account/password/password_reset_complete.html'),
            name="password_reset_complete"),      

] 

faceattandance/faceattandance/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

student/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from Attendance.views import select_sub

app_name ="student"

urlpatterns = [

    path('profile/', views.student_profile,name="student_profile"),
    path('logout/', views.student_logout,name="student_logout"),
    path('dashboard/', views.student_dashboard,name="student_dashboard"),
    path('time_table/',views.time_table,name="time_table"),
    path('report/',views.attendance_report,name="attendance_report"),
  
]

student/models.py
from django.db import models



# Create your models here.

student/forms.py
from django.contrib.auth.forms import User
from django.contrib.auth.forms import UserChangeForm
from django import forms
from account.models import User,Teacher,Student,Subject
from Attendance.models import TimeTable,Student_attendance
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.forms import ModelForm

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    password = None
    class Meta:
        model = User
        fields = ['username','email',]

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['first_name','last_name','roll_no','department','semester','image','contact_no']


class SelectSubForm(forms.ModelForm):
    class Meta:
        model = Student_attendance
        fields = ['subject']

    def __init__(self, user, *args, **kwargs):
        super(SelectSubForm, self).__init__(*args, **kwargs)
        self.fields['subject'].queryset = Subject.objects.filter(department_id = user.student.department,semester = user.student.semester)
       

student/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages, auth
from django.db import transaction
from django.contrib.auth.forms import UserChangeForm
from student.forms import ProfileUpdateForm, UserUpdateForm
from Attendance.models import TimeTable, Student_attendance
from account.models import Department
from django.db.models import Count
from django.core.mail import send_mail
import datetime
import matplotlib.pyplot as plt
import base64
from io import BytesIO
import pandas as pd
import numpy as np


@login_required
def time_table(request):
    dept = request.user.student.department
    sem = request.user.student.semester
    m1 = TimeTable.objects.filter(department_id=dept, sem=sem)
    m2 = m1
    return render(request, 'student/time_table.html', {'m1': m1, 'm2': m2})


@login_required
def student_dashboard(request):
    return render(request, 'student/student_portal.html')


@login_required
def student_profile(request):
    if request.method == "POST":
        fm = UserUpdateForm(request.POST, instance=request.user)
        fm1 = ProfileUpdateForm(request.POST,
                                request.FILES,
                                instance=request.user.student)
        if fm.is_valid() and fm1.is_valid():
            fm.save()
            fm1.save()
            messages.success(request, f"Your profile has updated!!!")
            return redirect('student:student_profile')
    else:
        fm = UserUpdateForm(instance=request.user)
        fm1 = ProfileUpdateForm(instance=request.user.student)

    return render(request, 'student/student_profile.html', {'fm': fm, 'fm1': fm1})


@login_required
def student_logout(request):
    auth.logout(request)
    return redirect('home')


@login_required
def training_webcam(request):
    return render(request, 'Attendance/training_webcam.html')


def get_graph():
    buffer = BytesIO()
    plt.savefig(buffer, formate='png')
    buffer.seek(0)
    image_png = buffer.getvalue()
    graph = base64.b64encode(image_png)
    graph = graph.decode('utf-8')
    buffer.close()
    return graph


def get_plot(x,y,a,b):
    plt.switch_backend("AGG")
    plt.title("Per day subject attended",fontsize = 16)    
    plt.plot(x,y,label="week1")
    plt.plot(a,b,label="week2")
    plt.xlabel("Week day ",fontsize = 14)
    plt.ylabel("Lecture attended per week",fontsize = 14)
    plt.legend()    
    graph = get_graph()
    return graph
    
def get_pie(x):
    plt.switch_backend("AGG")
    plt.title("Week wise present absent",fontsize = 20)
    colors = ["green","red"]
    labels="Present","Absent"
    plt.pie([x,15-x],explode=(0, 0.1), labels=labels,
                autopct='%1.1f%%', shadow=True, startangle=90,textprops={'fontsize': 16},colors=colors)
    graph = get_graph()
    return graph

def get_bar(x,y,a,b1):
    b = []
    for (i,k) in zip(a,b1):
        for j in x:
            if(j == i):
                b.append(k)
                break
    
    plt.figure(figsize=(100,100))
    plt.switch_backend("AGG")  
    
    X_axis1 = np.arange(len(x))
    plot = plt.bar(X_axis1 - 0.2, y, 0.4, label = 'Week1')
    plt.xticks(X_axis1, x, rotation=45)    
    
    X_axis2 = np.arange(len(a))
    plt.bar(X_axis2 + 0.2, b, 0.4, label = 'Week2')
        
    plt.title("Attendance of last week in %",fontsize = 16)
    plt.xlabel("Subjects",fontsize = 14)
    plt.ylabel("Percentage(%) of attendance",fontsize = 14)
    plt.legend()
    plt.tight_layout()
    graph = get_graph()
    return graph


@login_required
def attendance_report(request):
    stu = request.user.student
    attend_data = Student_attendance.objects.filter(student = stu)
    
    a = [x.subject for x in attend_data]
    b = [x.attend_date for x in attend_data]
    c = [x.attend_time for x in attend_data]
    d = [x.status for x in attend_data]
    
    dictionary = {
        "Subject": a,
        "Attend_date": b,
        "Attend_time": c,
        "Status": d,
    }
    df = pd.DataFrame(dictionary)
    
    df["Attend_date"] = pd.to_datetime(df["Attend_date"], errors='coerce')
    df["Day"] = df["Attend_date"].dt.day_name()
    df["Week"] = df["Attend_date"].dt.week
    df["Status"] = df["Status"].astype(int)
    df["Subject"] = df["Subject"].astype(str)
    lecture = [3,3,3,2,4]
    week_group = df.groupby(df["Week"])
    
    g1 = week_group.get_group(17)

    g2 = week_group.get_group(18)
    
    g1["day_sum"] = g1.groupby("Day")["Status"].transform('sum')
    #week1_day_attend = get_plot(g1["Day"],g1["day_sum"]) 
        
    g1["sub_sum"] = g1.groupby("Subject")["Status"].transform('sum')
    g = g1[["Subject","sub_sum"]].drop_duplicates()
    g["total_lec"] = lecture
    
    g2["day_sum"] = g2.groupby("Day")["Status"].transform('sum')
    #week2_day_attend = get_plot(g2["Day"],g2["day_sum"])     
    
    g2["sub_sum"] = g2.groupby("Subject")["Status"].transform('sum')
    g3 = g2[["Subject","sub_sum"]].drop_duplicates()
   
    count = 0
    lec = []
    for l in lecture:
        lec.append(l)
        count += 1
        if(count > len(g3["sub_sum"])):
            break
    
    sum1 = g["sub_sum"].sum()
    sum2 = g3["sub_sum"].sum()
    
    if(((sum1+sum2)/2<15) and datetime.datetime.now().hour < 12):
        
        perc = ((sum1+sum2)/2)*(100/15)
        send_mail(f"Alert! Low Attendace",f"Good Afternoon {request.user.student.first_name} {request.user.student.last_name} This is to notify you that your attendance is only {perc}% which is very low. Please be on time for next lecture."
                ,"anchallsm2000@gmail.com",[request.user.email],fail_silently = False)
        
    week_day_attend = get_plot(g1["Day"],g1["day_sum"],g2["Day"],g2["day_sum"])
    week_sub_attend = get_bar(g["Subject"],[(j/i)*100 for (i,j) in zip(g["total_lec"],g["sub_sum"])],g3["Subject"],[(j/i)*100 for (i,j) in zip(lecture,g3["sub_sum"])])
    
    return render(request, 'student/report.html', {"a": attend_data, "b": week_day_attend,"c": week_sub_attend,"d":get_pie(sum1),"e":get_pie(sum2)})

student/templates/student/base1.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel=" shortcut icon" href="{% static 'account/logo.png' %}" type="image/png"> 
    <!-- Jquery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <!-- Bootstrap -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- google fonts and google icon -->
    <link href='https://fonts.googleapis.com/css?family=Oxygen:400,300,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Lora' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    {% block css %}
    
    {% endblock %}
    <style>
        img{
            width:80%;
        }
    </style>
    {% block head %}
 
    {% endblock %}
</head>
<body style="background-color: #f7f7f7;">
    
   <div class="container-fluid">
        <div class="row">
            <div class="col-md-12 px-0">
                <nav class="navbar navbar-expand navbar-dark bg-dark">
                    
                    <a href="{% url 'student:student_dashboard' %}" class="navbar-brand">Student DashBoard</a>
                    <ul class="navbar-nav ml-auto">
                        
                        
                        <li class="nav-item mr-2">
                            <!-- {% block welcome %}{% endblock %} -->
                            <a href="#" class="nav-link">Welcome, {{user.username}}</a>
                        </li>
                        <li class="nav-item mr-2">
                            {% block profile %}{% endblock %}
                        </li>
                        <li class="nav-item mr-2">
                            
                            <a href="{% url 'student:student_logout' %}" class="btn btn-outline-light">Logout</a>
                        </li>
                        <!-- <li class="nav-item">
                            <a href=""  class=" btn btn-outline-light" data-toggle="modal"
                            data-target="#mymodal">Login</a>
                        </li> -->
                    
                    </ul>
                </nav>
            </div>      
        </div>
    </div>

  {% block myblock %}
      
  {% endblock %}
        

    <div style="margin-top: 10px;" class="container-fluid">
        <div class="row bg-dark text-light p-5">
           <div class="text-center">
               <p>Anchal Maurya</p>
               <a href="#">anchallsm2000@gmail.com</a>
           </div>
        </div>
   </div>
   
</body>
</html>

student/templates/student/report.html
{% extends 'student/student_portal.html' %}
{% load static %}
{% block title %}Report | {{request.user.username}}{% endblock title %}

{% block css %}    
  <style>
    
  </style>
{% endblock %}

{% block dashboard %}
    <div style="margin-top:40px" class=" r col-md-10 col-lg-10">
        {% for message in messages %}
        <div class="alert alert-success alert-dismissible fade show">
            <strong>{{ message }}.</strong>
            <button type="button" class="close" data-dismiss="alert">&times;</button>
        </div>
       
        {% endfor %}
    
    <h1>Attendance Report of last two week</h1>

    <div class="row dash-menu">		
	<p class="heading">Lecture attended per subject(%)</p>
		{% if c %}
            <img src="data:image/png;base64,{{c|safe}}">
        {% endif %}
	</div>
		
	<div class="row dash-menu">
	<div><p class="heading">Lecture attended per day</p></div>
		{% if b %}
            <img src="data:image/png;base64,{{b|safe}}">
        {% endif %}
	</div>
	
	<div class="row dash-menu">
	<p class="heading">Week-1 Week-2: present and absent</p>
		<div class="row piechart">
            <div class="col-lg-6 col-md-6">
				{% if d %}
					<img src="data:image/png;base64,{{d|safe}}">
				{% endif %}
			</div>
            <div class="col-lg-6 col-md-6">
			{% if e %}
				<img src="data:image/png;base64,{{e|safe}}">
			{% endif %}
			</div>
        </div>
	</div>
		<p style="color: red;">Please check your email inbox regarding low attendace...!!</p>

	 <div class="row dash-menu">
	 <div><p class="heading">All Your attendance data</p><div>
            <table border="1px solid">
                    <tr>
                        <th>Subject</th>
                        <th>Date</th>
                        <th>Attend_time</th>
                        <th>Status</th>
                    </tr>
                    {% for a1 in a %}
                    <tr>
                        <td>{{a1.subject}}</td>
                        <td>{{a1.attend_date}}</td>
                        <td>{{a1.attend_time}}</td>
                        <td>{{a1.status}}</td>
                    </tr>
                    {% endfor %}
            </table>
        </div>
		
    </div>
       
{% endblock %}

student/templates/student/select_sub.html
{% extends 'student/student_portal.html' %}
{% load static %}
{% block title %}Attendance| {{request.user.username}}{% endblock title %}

{% block css %}    
  <style>
    
  </style>
{% endblock %}

{% block dashboard %}
    <div style="margin-top:40px" class=" r col-md-10 col-lg-10">
        {% for message in messages %}
        <div class="alert alert-success alert-dismissible fade show">
            <strong>{{ message }}.</strong>
            <button type="button" class="close" data-dismiss="alert">&times;</button>
        </div>
        {% endfor %}
        <div class="row dash-menu">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}        
                <p style="font-size: 30px;">Select Subject</p>
                <div class="row">
                    <div class="col-lg-5 col-md-5">{{fm.subject.label_tag}}</div>
                    <div class="col-lg-5 col-md-5">{{fm.subject}}</div>
                </div>
                <div class="col-lg-8 col-md-8 " style="margin-top: 30px;">
                    <button class="btn btn-secondary" type="submit">Open Camera</button>
                </div>
            </form>
        </div>
    
    </div>
       
{% endblock %}

student/templates/student/student_portal.html
{% extends "base_dashboard.html" %}
{% load static %}

{% block user_type %}
    <a href="{% url 'student:student_dashboard' %}" class="navbar-brand dash">Student DashBoard</a>
{% endblock %}

{% block myblock %}
{% if user.is_superuser or user.is_teacher %}
    <div class="container">
        <div class="row">
            <div class="col-md-12 mt-4">
                <div class="jumbotron">
                    <h1>Sorry Mr./Miss {{user.username}} You are not allowed Here</h1>
                </div>
            </div>
        </div>
    </div>
{% else %}

{% block profile %} 
<a href="{% url 'student:student_profile' %}" class="btn btn-outline-light">Profile</a>{% endblock %}
<div class="container-fluid my-0" style="margin-top: 5px;" >
    <div class="row">
        <!-- left side menu -->
        <div class="col-md-2 bg-dark py-5">
            <nav class="navbar navbar-dark">
                <a href="{% url 'student:student_dashboard' %}" class="navbar-brand">
                    <div class="text-center">
                        {% if request.user.student.image %}
                        <img class="rounded-circle profile-img" src="{{request.user.student.image.url}}" width="200" height="170">
                        {% else %}
                            <img class="rounded-circle profile-img" src="{% static '/student/profile.png' %}" width="170" height="170">
                        {% endif %}             
                        <p class="username">{{user.username}}</p>
                    </div>
                </a>                
                <ul class="navbar-nav border-bottom">                   
                    <li class="nav-item">
                        <a href="{% url 'account:change_password_stu' %}" class="nav-link">Change Password</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'student:student_profile' %}" class="nav-link">Edit Profile</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'student:attendance_report' %}" class="nav-link">Attendance Report</a>
                    </li>   
                </ul>

            </nav>
        </div>
		<!--user:shetty11,pass:12345#qwA -->
        <!-- right side menu -->
        <div class="container">
        {% block dashboard %}
            <div style="margin-top:40px" class="col-md-10 col-lg-10">                
                <!-- 1st menu -->  
                {% for message in messages %}
                    <div class="alert alert-success alert-dismissible fade show">
                        <strong>{{ message }}.</strong>
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                    </div>
                    {% endfor %} 

                <div class="row dash-menu">
                    <div class="col-md-4 col-lg-4">                    
                        <img src="{% static 'student/attendance.jpg' %}">
                        <p class="dash-stu-heading">Give Attendance</p>
                    </div>
                    <div class="col-md-6 col-lg-6 menu-desc">                   
                        <p class="dash-stu-descr">Give your attendance here by clicking on "give attendance" button. 
                                                    Then you need to select subject of which you want to give attendance. 
                                                    </p>
                        <div class="dash-stu-btn">
                            <a class="btn btn-secondary" href="{% url 'Attendance:select_sub' %}">Give Attendance</a>
                        </div>                     
                    </div>
                </div>    
    
                <!-- 2nd menu -->      
                <div class="row dash-menu">
                    <div class="col-md-4 col-lg-4">
                        <img src="{% static 'student/tt.png' %}">
                        <p class="dash-stu-heading">Time Table</p>
                    </div>
                    <div class="col-md-6 col-lg-6 menu-desc">
                        <p class="dash-stu-descr"> Click here to see time table of your respective departement and semester. </p>
                        <div class="dash-stu-btn">
                            <a class="btn btn-secondary" href="{% url 'student:time_table' %}">Time Table</a>
                        </div>
                    </div> 
                </div>         
                                
                <!-- 3rd menu -->
                <div class="row dash-menu">  
                    <div class="col-md-4 col-lg-4">
                        <img src="{% static 'student/report.png' %}">
                        <p class="dash-stu-heading">Attendance Report</p>
                    </div>
                    <div class="col-md-6 col-lg-6 menu-desc">
                        <p class="dash-stu-descr"> See your all your attendance history of previous week,previous month
                        Check the backlog and other activity of attendance.</p>
                        <div class="dash-stu-btn">
                            <a class="btn btn-secondary" href="{% url 'student:attendance_report' %}">See Report</a>
                        </div>
                    </div>
                </div>
                
            </div>
            {% endblock %}
        </div>
    </div>
</div>
{% endif %}

{% endblock %}

student/templates/student/student_profile.html
{% extends 'student/student_portal.html' %}
{% load static %}
{% block title %}Profile | {{request.user.username}}{% endblock title %}

{% block dashboard %}

<div style="margin-top:40px" class=" r col-md-10 col-lg-10">
  {% for message in messages %}
  <div class="alert alert-success alert-dismissible fade show">
    <strong>{{ message }}.</strong>
    <button type="button" class="close" data-dismiss="alert">&times;</button>
  </div>
{% endfor %}
  <div class="row dash-menu">
    <form action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}        
          <p style="font-size: 30px;">Profile Setting</p>
          <div class="row">
            <div class="col-lg-5 col-md-5">{{fm.username.label_tag}}</div>
            <div class="col-lg-5 col-md-5">{{fm.username}}</div>
          </div>

          <div class="row">
            <div class="col-lg-5 col-md-5">{{fm.email.label_tag}}</div>
            <div class="col-lg-5 col-md-5 dbox">{{fm.email}}</div>
          </div>
          <div class="row">
            <div class="col-lg-5 col-md-5">{{fm1.first_name.label_tag}} </div>
            <div class="col-lg-5 col-md-5 dbox">{{fm1.first_name}}</div>
          </div>
          <div class="row">
            <div class="col-lg-5 col-md-5">{{fm1.last_name.label_tag}}</div>
            <div class="col-lg-5 col-md-5 dbox">{{fm1.last_name}}</div>
          </div>
          <div class="row">
            <div class="col-lg-5 col-md-5">{{fm1.roll_no.label_tag}}</div>
            <div class="col-lg-5 col-md-5 dbox">{{fm1.roll_no}}</div>
          </div>
          <div class="row">
            <div class="col-lg-5 col-md-5"> {{fm1.semester.label_tag}} </div>
            <div class="col-lg-5 col-md-5 dbox">{{fm1.semester}}</div>
          </div>
          <div class="row">
            <div class="col-lg-5 col-md-5">{{fm1.contact_no.label_tag}} </div>
            <div class="col-lg-5 col-md-5 dbox">{{fm1.contact_no}}</div>
          </div>
          <div class="row">
            <div class="col-lg-5 col-md-5"> {{fm1.department.label_tag}}  </div>
            <div class="col-lg-5 col-md-5 dbox">{{fm1.department}}</div>
          </div>
          <div class="row">
            <div class="col-lg-5 col-md-5"> {{fm1.image.label_tag}} </div>
            <div class="col-lg-5 col-md-5 dbox">{{fm1.image}}</div>
          </div>
                        
          <div class="col-lg-8 col-md-8 " style="margin-top: 30px;">
            <button class="btn btn-secondary" type="submit">Save changes</button>
          </div>           
    </form>
  </div>

</div>
{% endblock %}

student/templates/student/time_table.html
{% extends 'student/student_portal.html' %}
{% load static %}
{% block title %}Time Table | {{request.user.username}}{% endblock title %}

{% block css %}    
  <style>
    .time{
      font-size: 30px; 
      border-bottom: rgb(136, 136, 138) solid 5px;
      width: 150px;
    }
    table{
      border-radius: 20px;
    }
    th,tr,td{
      padding: 20px;
      border-bottom: rgb(219, 216, 216) 1px solid;
      color: #777;
    }
    th{
      color: rgb(87, 87, 87);
      font-size: 20px;
    }
  </style>
{% endblock %}

{% block dashboard %}
<p class="time">Time Table</p>
<table class="dash-menu" align=center>

      <tr align=center>
        <th colspan=6>{{request.user.student.department}}</th>
      </tr>
        <tr colspan=6 align=center>
        <th>Time</th>
        <th>Monday</th>
        <th>Tuesday</th>
        <th>Wednesday</th>
        <th>Thursday</th>
        <th>Friday</th>
      </tr>
      
      {% regroup m1 by start_time as timelist %}
    <tbody align="center">  
      {% for row in timelist %}
      <tr>
        {% if row.grouper == '11:00' %}
        <th rowspan=2>{{row.grouper}}-11:50 </th>
        {% elif row.grouper == '12:00' %}
        <th rowspan=2>{{row.grouper}}-12:50 </th>
        {% elif row.grouper == '02:00' %}
        <th rowspan=2>{{row.grouper}}-2:50 </th>
        {% endif %}
      </tr>  

      <tr colspan=5>       
        {% for r in row.list %} 
        <td>{{r.subject_id}}<br>({{r.teacher}})</td>      
        {% if r.day == '-' %}
        <td>-</td>
        {% endif %}
        {% endfor %}
      </tr>      
      {% endfor %}
    </tbody>    
  </table> 
        
{% endblock %}