FaceAttendance/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('account/',include('account.urls')),
    path('student/',include('student.urls')),
    path('teacher/',include('teacher.urls')),
    path('Attendance/',include('Attendance.urls')),

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

account/urls.py
from django.contrib import admin
from django.urls import path,include
from account import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name='account' 

urlpatterns = [
    
    path('student/login/', views.student_login,name="student_login"),
    path('admin/login/', views.admin_login,name="admin_login"),
    path('student/register/', views.student_register.as_view(),name="student_register"),
    path('teacher/login/', views.teacher_login,name="teacher_login"),
    path('teacher/register/', views.teacher_register.as_view(),name="teacher_register"),
    path('change_password/student/$', views.change_password_stu,name="change_password_stu"),
    path('change_password/teacher/$', views.change_password_teach,name="change_password_teach"),

    path('password_reset/',auth_views.PasswordResetView.as_view(
            template_name='account/password/password_reset_form.html',
            email_template_name="account/password/password_reset_email.html",
            success_url=reverse_lazy('account:password_reset_done'),),
            name="reset_password"),

    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
            template_name='account/password/password_reset_done.html'), 
            name="password_reset_done"),

    path('password_reset/confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(
            template_name='account/password/password_reset_confirm.html',
            success_url=reverse_lazy('account:password_reset_complete'),), 
            name='password_reset_confirm'),

    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(
            template_name='account/password/password_reset_complete.html'),
            name="password_reset_complete"),      

] 

faceattandance/faceattandance/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

student/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from Attendance.views import select_sub

app_name ="student"

urlpatterns = [

    path('profile/', views.student_profile,name="student_profile"),
    path('logout/', views.student_logout,name="student_logout"),
    path('dashboard/', views.student_dashboard,name="student_dashboard"),
    path('time_table/',views.time_table,name="time_table"),
    path('report/',views.attendance_report,name="attendance_report"),
  
]

account/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User,AbstractUser

class Department(models.Model):
    department_id = models.IntegerField(primary_key = True)
    department_name = models.CharField(max_length = 50,blank = True)

    def __str__(self): 
        return str(self.department_name)

class Subject(models.Model):
    subject_id = models.CharField(max_length = 50,primary_key = True)
    subject_name = models.CharField(max_length = 50,blank = True)
    semester = models.CharField(max_length=10,blank = True)    
    department_id = models.ForeignKey(Department,on_delete=models.CASCADE,blank = True)

    def __str__(self): 
        return str(self.subject_name)

class User(AbstractUser):
    last_login = models.DateField(default=timezone.now)
    is_teacher = models.BooleanField(default = False)
    is_student = models.BooleanField(default = False)
    is_staff = models.BooleanField(default = True)
    is_active = models.BooleanField(default = True)
    email = models.EmailField(unique =True)
    
    def __str__(self): 
        return str(self.pk)

class Student(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,primary_key=True)
    first_name = models.CharField(max_length=50,blank = True)
    last_name = models.CharField(max_length=50,blank = True)
    roll_no = models.CharField(max_length=10,blank = True)
    semester = models.CharField(max_length=10,blank = True)
    contact_no = models.IntegerField(blank = True,null=True)
    image = models.ImageField(upload_to="images/",null=True)
    department = models.ForeignKey(Department,on_delete=models.CASCADE,null=True)

    def __str__(self): 
        return str(self.first_name) 

class Teacher(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,primary_key=True)
    first_name = models.CharField(max_length=50,blank = True)
    last_name = models.CharField(max_length=50,blank = True)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE,null=True)
    image = models.ImageField(upload_to="images/",null=True)
    department = models.ForeignKey(Department,on_delete=models.CASCADE,null=True)
     
        
    def __str__(self): 
        return str(self.first_name)

    

account/forms.py
from django.contrib.auth.forms import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import User,Teacher,Student,Department
from django.db import transaction
from django.forms import ModelChoiceField


class StudentSignUpForm(UserCreationForm):
        first_name = forms.CharField(max_length=50)
        last_name = forms.CharField(max_length=50)
        email = forms.EmailField(max_length = 100)
        #     roll_no = forms.CharField(max_length=10)
        #     semester_no = forms.CharField(max_length=10)
        department = forms.ModelChoiceField(queryset = Department.objects.all(),required = True)
        contact_no = forms.CharField(max_length=10,required = True)
                
        class Meta(UserCreationForm.Meta):
                model = User
        
        def clean(self):
                super(StudentSignUpForm,self).clean()
                first_name = self.cleaned_data.get('first_name')
                last_name = self.cleaned_data.get('last_name')
                contact_no = self.cleaned_data.get('contact_no')

                if first_name is None:
                        self.errors['first_name'] = self.error_class(['Firstname can not be empty*'])
                elif len(first_name)<2:
                        self.errors['first_name'] = self.error_class(['Firstname should be of atleast 2 character length*'])
                elif first_name is None:
                        self.errors['last_name'] = self.error_class(['Lastname can not be empty*'])
                elif len(first_name)<2:
                        self.errors['last_name'] = self.error_class(['Lastname should be of atleast 2 character length*'])
                elif contact_no is None:
                        self.errros['contact_no'] = self.errro_class(['Contact can not be empty*'])
                elif len(contact_no)<10 or len(contact_no)>10:
                        self.errros['contact_no'] = self.errro_class(['Contact no. should be 10 digit long*'])
                
                return self.cleaned_data

        @transaction.atomic
        def save(self):
                user = super().save(commit = False)
                user.email = self.cleaned_data.get('email')
                user.is_student = True
                user.is_teacher = False
                user.save()
                student = Student.objects.create(user = user)
                student.first_name = self.cleaned_data.get('first_name')
                student.last_name = self.cleaned_data.get('last_name')
                # student.stu_roll_no = self.cleaned_data.get('roll_no')
                student.department = self.cleaned_data.get('department')
                student.contact_no = self.cleaned_data.get('contact_no')
                student.save()
                return student


class TeacherSignUpForm(UserCreationForm):
        first_name = forms.CharField(max_length=50,required = True)
        last_name = forms.CharField(max_length=50,required = True)
        email = forms.EmailField(max_length = 100)
        department = forms.ModelChoiceField(queryset=Department.objects.all(),required = True)
        
        class Meta(UserCreationForm.Meta):
                model = User

        def clean(self):
                super(TeacherSignUpForm, self).clean()
                first_name = self.cleaned_data.get('first_name')
                last_name = self.cleaned_data.get('last_name')
                
                if first_name is None:
                        self._errors['first_name'] = self.error_class(['Firstname can not be empty*'])
                elif first_name.isdigit():
                        self._errors['first_name'] = self.error_class(['Firstname can not be digit*'])
                elif len(first_name)<2:
                        self._errors['first_name'] = self.error_class(['Firstname should be of atleast 2 character length*'])
                elif last_name is None:
                        self._errors['last_name'] = self.error_class(['Lastname can not be empty*'])
                elif last_name.isdigit():
                        self._errors['last_name'] = self.error_class(['Lastname can not be digit*'])
                elif len(last_name)<2:
                        self._errors['last_name'] = self.error_class(['Lastname should be of atleast 2 character length*'])
                
                return self.cleaned_data

        @transaction.atomic
        def save(self):
                user = super().save(commit = False)
                user.email = self.cleaned_data.get('email')
                user.is_student = False
                user.is_teacher = True
                user.save()
                teacher = Teacher.objects.create(user = user)
                teacher.first_name = self.cleaned_data.get('first_name')
                teacher.last_name = self.cleaned_data.get('last_name')
                # teacher.teach_sub = self.cleaned_data.get('teach_sub')
                teacher.department = self.cleaned_data.get('department')
                teacher.save()
                return teacher

FaceAttendance/views.py
from django.shortcuts import render, redirect

def home(request):    
    return render(request,'home.html')

account/views.py
from django.shortcuts import render,redirect,reverse,HttpResponseRedirect
from django.contrib.auth.forms import AuthenticationForm
from django.views.generic import CreateView
from account.forms import StudentSignUpForm,TeacherSignUpForm
from account.models import User,Teacher,Student
from django.contrib.auth import authenticate,login
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from student.views import student_dashboard
    
@login_required
def change_password_stu(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Your password is successfully updated!')
            return redirect('student:student_dashboard')
        else:
            messages.error(request, 'Please enter valid password(include num,symbol and char')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'account/change_password.html', {'form': form})
    
def change_password_teach(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Your password is successfully updated!')
            return redirect('account:change_password_teach')
        else:
            messages.error(request, 'Please enter valid password(include num,symbol and char')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'account/change_password1.html', {'form': form})

def admin_login(request):
    if request.method =="POST":
        form = AuthenticationForm(request=request,data=request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username,password=password)
            if user is not None:
                login(request,user)
                return redirect('Attendance:attendance')
            else:
                messages.error(request,"Username does not exist")
                return render(request,'account/admin_login.html',{'form':form})
        else:
            messages.error(request,"username or password is incorrect!!")
            return render(request,'account/admin_login.html',{'form':form})
                
    else:
        form = AuthenticationForm()
        return render(request,'account/admin_login.html',{'form':form})

#Student
def student_login(request):
    if request.method =="POST":
        form = AuthenticationForm(request=request,data=request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username,password=password)
            if user is not None:
                login(request,user)
                return redirect('student:student_dashboard')
            # else:
            #     messages.error(request,"username or password is incorrect!!")
            #     return render(request,'account/student_login.html',{'form':form})
        else:
            messages.error(request,"username or password is incorrect!!")
            return render(request,'account/student_login.html',{'form':form})
                
    else:
        form = AuthenticationForm()
        return render(request,'account/student_login.html',{'form':form})

class student_register(CreateView):
    form_class = StudentSignUpForm
    model = User
    template_name = 'account/student_register.html'

    def get_success_url(self):
        return reverse('account:student_login')

#Teacher
def teacher_login(request):
    if request.method =="POST":
        form = AuthenticationForm(request=request,data=request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username,password=password)
            if user is not None:
                login(request,user)
                return redirect('teacher:teacher_dashboard')
            # else:
            #     messages.error(request,"username or password is incorrect!!")
            #     return render(request,'account/student_login.html',{'form':form})
        else:
            messages.error(request,"username or password is incorrect!!")
            return render(request,'account/teacher_login.html',{'form':form})
                
    else:
        form = AuthenticationForm()
        return render(request,'account/teacher_login.html',{'form':form})

class teacher_register(CreateView):
    form_class = TeacherSignUpForm
    model = User
    template_name = 'account/teacher_register.html'

    def get_success_url(self):
        return reverse('account:teacher_login')

FaceAttendance/templates/base_dashboard.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel=" shortcut icon" href="{% static 'account/logo.png' %}" type="image/png"> 
    <!-- Jquery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <!-- Bootstrap -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- google fonts and google icon -->
    <link href='https://fonts.googleapis.com/css?family=Oxygen:400,300,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Lora' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    
    <link rel="stylesheet" href="/static/student/stu_profile.css?{% now 'U' %}">
    {% block css %}
    
    {% endblock %}
    <style>
        img{
            width:80%;
        }
    </style>
    {% block head %}
 
    {% endblock %}
</head>
<body style="background-color: #f7f7f7;">
    
   <div class="container-fluid">
        <div class="row">
            <div class="col-md-12 px-0">
                <nav class="navbar navbar-expand navbar-dark bg-dark">                    
                    {% block user_type %}                    
                    {% endblock %}

                    <ul class="navbar-nav ml-auto">                       
                        
                        <li class="nav-item mr-2">
                            <!-- {% block welcome %}{% endblock %} -->
                            <a href="#" class="nav-link">Welcome, {{user.username}}</a>
                        </li>
                        <li class="nav-item mr-2">
                            {% block profile %}{% endblock %}
                        </li>
                        <li class="nav-item mr-2">
                            <a href="{% url 'student:student_logout' %}" class="btn btn-outline-light">Logout</a>
                        </li>
                        <!-- <li class="nav-item">
                            <a href=""  class=" btn btn-outline-light" data-toggle="modal"
                            data-target="#mymodal">Login</a>
                        </li> -->
                    
                    </ul>
                </nav>
            </div>      
        </div>
    </div>

  {% block myblock %}
      
  {% endblock %}
        

    <div style="margin-top: 10px;" class="container-fluid">
        <div class="row bg-dark text-light p-5">
           <div class="text-center">
               <p>Ujala Maurya</p>
               <a href="#">ujalamaurya.um@gmail.com</a>
           </div>
        </div>
   </div>
   
</body>
</html>

FaceAttendance/templates/home.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>FaceAttendance</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- favicon file -->
    <link rel=" shortcut icon" href="{% static 'account/logo.png' %}" type="image/png"> 
    <!-- Jquery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <!-- Bootstrap -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- google fonts and google icon -->
    <link href='https://fonts.googleapis.com/css?family=Oxygen:400,300,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Lora' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <!-- Css file -->
    <link rel="stylesheet" href="/static/account/home.css?{% now 'U' %}">
    {% block homecss %}

    {% endblock homecss %}
    
    <!-- Jquery for image silder -->
    <script> window.initializerCarousel=()=>{ $("#carouselExampleIndicators").carousel({interval: 1000}); }</script>

 </head>

<body style="background-color: #f7f7f7;">

  <header>
      <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand navbarText" href="{% url 'home' %}">FaceAttendance</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item mr-2">
              <a class="navlink btn btn-outline-light" href="{% url 'account:admin_login' %}" >Admin</a>
            </li>
            <li class="nav-item mr-2">
              <a class="navlink btn btn-outline-light" href="{% url 'account:teacher_login' %}">Teacher</a>
            </li>
            <li class="nav-item mr-2">
              <a class="navlink btn btn-outline-light" href="{% url 'account:student_login' %}">Student</a>
            </li>              
          </ul>
        </div> 
      </nav>
    </header>

    <!-- Main body-image silder -->
    <div id="carouselExampleIndicators" class="carousel slide " data-ride="carousel">
     
	 {% block threeslide %}
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
      </ol>
   {% endblock threeslide %}
      <div class="carousel-inner" data-flickity='{"wraAround": true, "autoPlay": true}'>
        
       <div class="carousel-item active">
          <img class="d-block w-100" src="{% static 'account/home.jpg' %}" alt="First slide">
        </div>
        
        <div class="carousel-item">
          <img class="d-block w-100" src="{% static 'account/home1.jpg' %}" alt="Second slide">
        </div>

        <div class="carousel-item">
          <img class="d-block w-100" src="{% static 'account/home2.jpg' %}" alt="Third slide">
        </div>
   
        {% block content %}

        <div class="img-text">
          <h1>FaceAttendance</h1>
          <p class="c col-md-12 col-lg-12">FaceAttendance is web based attendance monitoring system using facial recognition technology. A facial recognition attendance system uses facial recognition technology to identify and 
            verify a person using the person's facial features and automatically mark attendance. 
            Managing attendance through face recognition is secure and faster way. A facial recognition 
			attendance system uses facial recognition technology to identify and verify a person using 
			the person's facial features and automatically mark attendance.
          </p>
        </div>
              
        {% endblock content %}
        
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
      
    </div>
    {% block content1 %}
    
    {% endblock content1 %}
  </div>
      
  <div class="container">
    
    <section class="text-gray-700 body-font col-lg-12">
            <div class="container px-5 py-24 mx-auto">
              <div class="xl:w-1/2 lg:w-3/4 w-full mx-auto text-center">
                <svg xmlns="http://www.w3.org/2000/svg" style="width: 50px; height: 50px" fill="currentColor" class="inline-block w-8 h-8 text-gray-400 mb-8" viewBox="0 0 975.036 975.036">
                  <path d="M925.036 57.197h-304c-27.6 0-50 22.4-50 50v304c0 27.601 22.4 50 50 50h145.5c-1.9 79.601-20.4 143.3-55.4 191.2-27.6 37.8-69.399 69.1-125.3 93.8-25.7 11.3-36.8 41.7-24.8 67.101l36 76c11.6 24.399 40.3 35.1 65.1 24.399 66.2-28.6 122.101-64.8 167.7-108.8 55.601-53.7 93.7-114.3 114.3-181.9 20.601-67.6 30.9-159.8 30.9-276.8v-239c0-27.599-22.401-50-50-50zM106.036 913.497c65.4-28.5 121-64.699 166.9-108.6 56.1-53.7 94.4-114.1 115-181.2 20.6-67.1 30.899-159.6 30.899-277.5v-239c0-27.6-22.399-50-50-50h-304c-27.6 0-50 22.4-50 50v304c0 27.601 22.4 50 50 50h145.5c-1.9 79.601-20.4 143.3-55.4 191.2-27.6 37.8-69.4 69.1-125.3 93.8-25.7 11.3-36.8 41.7-24.8 67.101l35.9 75.8c11.601 24.399 40.501 35.2 65.301 24.399z"></path>
                </svg>
                <p class="leading-relaxed text-lg">This project is developed by Anchal Maurya based on Django framework. <br> Hope You all will enjoy this and will get benefit.</p>
                <span class="inline-block h-1 w-10 rounded bg-blue-500 mt-8 mb-6"></span>
                <h2 class="text-gray-900 font-medium title-font tracking-wider text-sm">ANCHAL MAURYA</h2>
                <p class="text-gray-500">Django Developer</p>
              </div>
            </div>
          </section>

 
        </div>
   
    <footer>
      <div style="margin-top: 10px;" class="container-fluid">
        <div class="bg-dark text-light p-5">
           <div class="text-center">
               <p>Anchal Maurya</p>
               <a href="#">anchallsm2000@gmail.com</a>
           </div>
        </div>
   </div>
    </footer>
</body>
</html>